name: "Node.js CI"
description: "This action builds and tests a Node.js app"

inputs:
  node-version:
    description: 'The version of Node.js to use for building and testing.'
    required: false
    default: '16'
  node-cache:
    description: 'Package manager to use. Valid inputs: npm, yarn, pnpm.'
    default: "npm"
    required: false
  test-command:
    description: 'The custom command to run for testing the application.'
    required: false
    default: 'npm test'
  build-command:
    description: 'Command required to build the app'
    required: false
    default: 'npm run build'
  run-tests:
    description: 'Whether to run tests or not'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Build and test
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-cache }}
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Validate test commands
      if: ${{ inputs.run-tests == 'true' }}
      uses: ./.github/actions/utils/command-validator
      with:
        main-package: 'npm'
        valid-params: 'run test, run test:linter, run test:syntax'
        user-command: ${{ inputs.test-command }}
      id: validate-test-command
      
    - name: Run test commands
      shell: bash
      if: ${{ env.VALID == 'true' }}
      run: ${{ inputs.test-command }}

    - name: Validate build commands
      uses: ./.github/actions/utils/command-validator
      with:
        main-package: 'npm'
        valid-params: 'run build'
        user-command: ${{ inputs.build-command }}
      id: validate-build-command

    - name: Run build commands
      shell: bash 
      if: ${{ env.VALID == 'true' }}
      run: ${{ inputs.build-command }}
