apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scale
spec:
  scaleTargetRef:
    kind: Deployment
    name: main-nginx-ingress-controller
  minReplicaCount: 1
  maxReplicaCount: 20
  cooldownPeriod: 30
  pollingInterval: 1
  triggers:
  - type: elasticsearch
    metadata:
      addresses: http://elasticsearch.myapp:9200
      index: filebeat-*
      searchBody: >
        {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-1m"
                  }
                }
              },
              "must": {
                "match": {
                  "app_kubernetes_io_name": "nginx-ingress"
                }
              }
            }
          },
          "aggs": {
            "nginx_connections_active_keda": {
              "avg": {
                "field": "nginx_ingress_nginx_connections_active"
              }
            }
          },
          "size": 0
        }
      valueLocation: aggregations.nginx_connections_active_keda.value
      threshold: "100"