apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scale
  namespace: myapp
spec:
  scaleTargetRef:
    kind: Deployment
    name: main-nginx-ingress-controller
  minReplicaCount: 1
  maxReplicaCount: 20
  cooldownPeriod: 30
  pollingInterval: 30
  triggers:
  - type: elasticsearch
    metadata:
      addresses: http://elasticsearch:9200
      index: filebeat-*
      searchTemplateName: nginx_requests_keda
      valueLocation: aggregations.requests_per_minute.buckets.0.total_requests_or_zero.value
      threshold: "30"
      targetValue: "60"