name: api-sample-anthony-build

on:
  workflow_dispatch:

jobs:

  checkout_repository:
    runs-on: self-hosted
    steps:
    - name: Clean workspace
      run: rm -rf ${{ vars.REPO_API_SAMPLE_ANTHONY }}/

    - name: Checkout repository GitLab
      run: | 
        git clone https://${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@gitlab.com/${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}/${{ vars.REPO_API_SAMPLE_ANTHONY }}.git
        cd ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        ls -l
    
  create_artifact:
    runs-on: self-hosted
    needs: [checkout_repository]
    steps:
    - name: artifact packaging
      run: |
        mkdir -p ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        cp -R api-definition ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        cp -R pom.xml ${{ vars.REPO_API_SAMPLE_ANTHONY }}

  publish_artifact:
    runs-on: self-hosted
    needs: [create_artifact]
    steps:
    - name: algo2
      run: echo "hola algo2"