name: api-sample-anthony-build

on:
  workflow_dispatch:

jobs:

  create_publish_artifact:
    runs-on: self-hosted
    steps:
    - name: Clean workspace
      run: rm -rf ${{ vars.REPO_API_SAMPLE_ANTHONY }}/

    - name: Checkout repository GitLab
      run: | 
        git clone https://${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@gitlab.com/${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}/${{ vars.REPO_API_SAMPLE_ANTHONY }}.git
        cd ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        ls -l
    
    - name: create_artifact
      run: mkdir -p api-sample-anthony
    - name: paso 2
      run: cp -R api-definition api-sample-anthony
    - name: paso 3
      run: cp -R pom.xml api-sample-anthony

    - name: publish_artifact
      run: |
        echo "publish_artifact"