name: api-sample-anthony-build

on:
  workflow_dispatch:

jobs:

  checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout repository GitLab
      run: | 
        pwd
        rm -r api-sample-anthony
        git clone https://anthony.moreno.cisnero:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@gitlab.com/anthony.moreno.cisnero/api-sample-anthony.git
        cd api-sample-anthony
        ls -l
    
  create_artifact:
    runs-on: self-hosted
    needs: [Checkout]
    steps:
    - name: algo
      run: echo "hola algo"

  publish_artifact:
    runs-on: self-hosted
    needs: [create_artifact]
    steps:
    - name: algo2
      run: echo "hola algo2"