name: api-sample-anthony-build

on:
  workflow_dispatch:

jobs:

  create_publish_artifact:
    runs-on: self-hosted
    steps:
    - name: Clean workspace
      run: rm -rf ${{ vars.REPO_API_SAMPLE_ANTHONY }}/

    - name: Checkout repository GitLab
      run: | 
        git clone https://${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@gitlab.com/${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}/${{ vars.REPO_API_SAMPLE_ANTHONY }}.git
    
    - name: Create_artifact
      run: |
        cd ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        mkdir -p ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        cp -R api-definition ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        cp -R pom.xml ${{ vars.REPO_API_SAMPLE_ANTHONY }}

    - name: Publish_artifact
      run: |
        cd ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        ls -l
        az artifacts universal publish --organization https://dev.azure.com/Labs-DevOps/ --project='Axway' --scope project --feed api-sample-anthony --name api-sample-anthony --version ${{github.run_number}}.0.0 --description 'Universal Packages for job ${{ vars.REPO_API_SAMPLE_ANTHONY }} with version ${{github.run_number}}' --path api-sample-anthony/