name: api-sample-anthony-build

on:
  workflow_dispatch:

jobs:

  create_publish_artifact:
    runs-on: self-hosted
    steps:
    - name: Clean workspace
      run: rm -rf ${{ vars.REPO_API_SAMPLE_ANTHONY }}/

    - name: Checkout repository GitLab
      run: | 
        git clone https://${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@gitlab.com/${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}/${{ vars.REPO_API_SAMPLE_ANTHONY }}.git
    
    - name: create_artifact
      run: |
        cd ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        mkdir -p ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        cp -R api-definition ${{ vars.REPO_API_SAMPLE_ANTHONY }}
        cp -R pom.xml ${{ vars.REPO_API_SAMPLE_ANTHONY }}

    - name: publish_artifact
      run: |
        echo "publish_artifact"