name: api-sample-anthony

on:
  workflow_dispatch:

jobs:

  checkout:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get-APIs
      run: |
        #!/bin/bash
        alias apim=apim.sh
        apim api get -a /api/v1/sample-anthony -s prd8252