name: api-sample-anthony-build

on:
  workflow_dispatch:

jobs:

  clean_workspace:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
      - run: echo Hello World

  checkout:
    runs-on: self-hosted
    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
    - run: echo Hello World
    - name: Checkout repository GitLab
      run: | 
        git clone https://anthony.moreno.cisnero:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@gitlab.com/anthony.moreno.cisnero/api-sample-anthony.git
        cd api-sample-anthony
        ls -l
    
  create_artifact:
    runs-on: self-hosted
    needs: [Checkout]
    steps:
    - name: algo
      run: echo "hola algo"

  publish_artifact:
    runs-on: self-hosted
    needs: [create_artifact]
    steps:
    - name: algo2
      run: echo "hola algo2"