name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.js CI
        uses: ./.github/actions/nodejs/ci
        with:
          node-version: '16'
          node-cache: 'npm'
          test-command: 'npm run test'
          build-command: 'npm run build'
          run-tests: 'true'

      - name: run ls
        run: pwd
      

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: /home/runner/work/simple-app/simple-app/
          push: true
          tags: c0lima/node-app:latest